### ISSUE TITLE
Sandwich plate thickness + length

### ISSUE THREAD

**Issue by carlygeehr** [jdleslie/fuse-faux-letterpress#1]
Hi there,
I'm following in your footsteps trying to do all of my wedding paper goods on a Fuse, and I'm having some issues with the sandwich misbehaving... Specifically, I'm using 8"x8" sheets of 1/2" and 3/8" acrylic (with the paper & photopolymer plate in between) aligned with a few delrin pins and having a ton of trouble with the plates tilting as they pass through the rollers. Did you experience this at all? I'm wondering if it's because my plates are so much shorter than yours. I'm loathe to go spend over $100 on thick acrylic if I don't need to... It seems like with the L letterpress the hinged nature of the sandwich prevents the same tilting from happening after the plate passes through the rollers. I'm getting a loud pop after the pressure is released, which I don't think is good.

Not sure if you check this at all, but wanted to say a hearty thank you for your thorough documentation!!
-Carly

**Comment by jdleslie** [comment]
Great to hear you are having a go with this! 
- 8" x 8" sounds small for both the top and bottom plates-- how big is your workpiece?
- Is your top plate staying on the pins as it tilts/pops?
- Do you have any photos of your setup?

The bottom plate needs to be extra-long to ensure it does not tilt or bend while the paper is under compression by the rollers. 
- Good rule of thumb is that the base should be supported on both sides of the rollers whenever the top plate is under compression. I added a 1/4 piece of acrylic using double sided tape to the outfield side to make the bottom plate level.
- Having extra length makes it easier to push/pull the workpiece in and out of the rollers during production runs. You only need to crank the handle when the top plate is under compression (so after the top plate pops free you can quickly slide the base through a few more inches to make it easy to remove the workpiece)
- You might try 3/4" MDF as a more budget-friendly alternative to acrylic that is available from Lowes/Home Depot (they will even cut it for you).
- I never really run the entire bottom plate out of the rollers. I have enough length that I can load paper on both sides and run the press in both directions without the bottom plate ever losing contact with the lower roller.

The top plate normally tilts as it enters the rollers and pops back up as it exits. 
- In the beginning I found this really disconcerting and used extra pieces of photopolymer, cardboard, and Delrin to limit the movement. It turned out I was over-inking, and the ink on the sides of the photopolymer would smear on the piece when the top plate moved.
- Eventually I stopped worrying about it-- as long as the paper is centered under the top plate with a few inches of empty lead-in and lead-out space the movement of the top plate seems to not be a problem as the photopolymer has already deposited its ink when it pops up, and the weight of the top plate is not really enough to damage the paper (the force of the rollers is needed to make an impression on the paper). The key for me was to ensure there is no ink on the sides of the photopolymer (e.g. letters)
- When printing large areas with metallic ink, uniformity of pressure is important and visible in the result. Specifically the "dive" at the start of the pass squeezes out extra ink (guessing the top plate acts a a lever), and the plate seems to rebound a bit so the remainder of the section is uniform and has thicker (shinier!) coverage. If you run your press from both directions you will see the imperfection is always on the side that passes through the press first. Did not seem to affect non-metallic inks (e.g black)-- the shiny-ness of metallic inks is what makes it more clear. Even with metallic ink the imperfection is subtle enough that nobody else seems to notice...

Good luck, and feel free to reach out or add content to this wiki as your project progresses!

**Comment by carlygeehr** [comment]
I'm SO GRATEFUL for you!! I figured this comment would get lost into the abyss - this is far better a response than I could have hoped for!

The length is certainly a problem. I actually found a vendor online who somehow miraculously sells acrylic for criminally low prices (http://freckleface.com/) so I'm going to pull the trigger on a 24"x12" piece of 1/2" for the base. Do you think that's big enough? How long should the top plate be? I haven't designed anything yet, aside from the save the dates (4"x6") and bridesmaid cards (which I can easily do even with my current shoddy setup) so it's all negotiable. Something between 12 & 24" long?

I realized the violent popping sound was due to the fact that my base acrylic plate was WAY out of tolerance!! There's a ~.030" difference between each side. Actually, trying to feed it in backwards it won't even enter/fit through the rollers. I just found it lying around my lab, hoping whatever piece I order from Freckleface will be in tolerance and that will fix that issue. I think 8" being so short, I was getting a huge amount of tilting because there's really only 2" between the end of the photopolymer plate and the edge of the acrylic... 

One fun thing I'm still trying to play with is how to produce my "photopolymer" plates. So far I've been laser etching them with mixed results - they get really warped so I've been flattening them with a heat gun, but they're never _really_ flat again. Makes inking interesting. My next thought is to use my lab's ultra high-def polyjet printer, but there will be issues with those, too... Alas, I may just have to order from Boxcar! I run a mechanical engineering lab at Stanford and figured there had to be a way to do it myself :-)

Thank you SO much for your help! I will absolutely add photos and keep you updated. It's shocking to me that there isn't more information about this on the internet!!! (Maybe we're just a special brand of crazy.)

**Comment by jdleslie** [comment]
Given the size of the machine, I planned for 8.5"x11" stock. I was not sure whether the paper would need to run through in portrait or landscape orientation (turns out portrait, that is with the 11" side parallel to the rollers, works fine). Portrait involves less cranking per pass.

You might be able to remove a few inches from the top plate width, but then again, it might be worth the extra cranking to have more margin for error...

## Materials

Here is what I used (on my second try):
![TAP Plastics receipt](http://jdleslie.smugmug.com/Projects/FuseLetterpressWiki/i-bwRWfLv/0/O/Tap%20Plastic%20Receipt.jpg)

| Length | Width | Thickness | Material | Source | Purpose |
| --- | --- | --- | --- | --- | --- |
| 32" | 12" | 1/2" (wiki says 3/4", which is a mistake) | acrylic (clear) | TAP Plastics ($54.67) | Base plate, could be made shorter, but too long is better than too short |
| 14" | 12" | 3/8" | acrylic (clear) | TAP Plastics ($18.08 each) | Top plate (made two of them, which did not end up saving time as I'd hoped, as printing takes lots of time but setup comparatively less) |
| 4" | 12" | 1/4" | acrylic (clear) | TAP Plastics ($2.90) | Outfeed rest for base plate, affixed with double sided tape |
| 36" | n/a | 1/4" diameter | Delrin rod | TAP Plastics ($1.80) | Peg stock |
| 384mm | 384mm | 1.5mm | Delrin sheet | [Ponoko](http://ponoko.com) ($21.00) | Brayer support for inking (see [brayer-tools.svg](https://github.com/jdleslie/fuse-faux-letterpress/blob/master/brayer-tools.svg)) |
| 24" | 12" | 1/4" | plate glass | Salvaged from a neighbor's plant stand on trash day | Brayer palette (mixing ink, inking plate, etc.) |

I sourced acrylic from [TAP Plastics in San Mateo](https://www.tapplastics.com/about/locations/detail/san_mateo_ca), which worked fine (and did not involve waiting for UPS). At the time (April 2015) they stocked Evonik Acrylite GP as their standard acrylic sheet product, which was reasonably flat.

## Plates

Photopolymer plates are low-tech to produce-- the process for exposing them looks very much like [etching a PCB with photo-resist](http://fritzing.org/learning/tutorials/pcb-production-tutorials/diy-pcb-etching/) or producing a print in a darkroom. The plates themselves are basically a 2.5d design, so I imagine it might be possible to 3D print them on a high-resolution machine (Boxcar prints them 1:1 at 1200dpi) assuming a suitable material...

I considered laser cutting the plates on a more laser-friendly material, but ended up ordering from Boxcar after playing with one of their samples-- the polymer material is very well suited to this application, and they clearly have their production process fully debugged. 

At the start of my letterpress project I had a lot of trouble just getting ink applied in a consistent way, so paying for plates seemed like a good way to limit risk and keep my printing project on schedule. I would be interested to learn more about DIY plates...

## &c.

I've uploaded my design for the brayer support (laser cut 1.5mm Delrin sheet, though any material that does not ruin the rubber brayer would be suitable) and will make some updates to the wiki. I never really finished/checked these notes, and see some internal inconsistencies and spelling mistakes.

Happy printing!

**Comment by carlygeehr** [comment]
I wish I'd checked this before placing my order! But I did ok - ordered a 32" long sheet of 1/2" and a 16" long sheet of the 3/8". I guess TAP isn't as expensive as I'd previously thought.. I may be saving a few dollars but it's basically a wash when shipping is included. Ah well!

At present I'm [ProJet](http://www.3dsystems.com/3d-printers/professional/projet-3500-hdmax)-ing a test plate (0.060" thick, 0.047" relief) to see if there's any way I could use that instead of the acrylic. (I'm not optimistic there's a way to remove the support material without warping it just as badly as the laser-etched acrylic.) Otherwise, it's a big Boxcar order for me!

**Comment by carlygeehr** [comment]
Just wanted to give you an update - I will post photos as soon as I'm able to take some decent ones (which will require some cleanup on my part).

# Plates

The UHD ProJet plate was a success - I used Tinkercad to quickly create my 3d plate file (because I know SolidWorks HATES bezier curves...) (_and, note to anyone else who stumbles upon this thread and finds this useful - when exporting SVG from Illustrator for import into Tinkercad: in the SVG save dialog box options, under Advanced Options, select CSS Properties: "Style Elements", or else you get crazy errors trying to import_) and was able to chip off the layer of wax well enough to take it for a spin. It made a great impression and is totally usable, but it's actually slightly more expensive than just going with Boxcar.

So... I went with Boxcar! I just got my plates and they look great. This run is just for Save the Dates, figure I should see if I'm up for doing the full invitation suite before diving in all the way.

# Materials

My order from Freckleface came in, as I mentioned above I got a 32" long 1/2" sheet and 16" long 3/8" sheet. I ordered my paper from cutcardstock.com and after some testing am somewhat regretting the choice (more on that later)

_Question for you_ - where along the 32" long sheet did you mount the pins? In the photos it looks like you biased towards the right hand side (if feeding left to right through the rollers) so that the plate is steady for removal. Would you change where you mounted these or would you recommend I do the same?

# Initial Issues

For my bridesmaid cards, I wanted to do a simple blind impression, no ink. My initial trials with my laser etched plates were on Strathmore 300 series Bristol board (100# weight, which I use for drawings) and the impressions were beautiful. I stupidly ordered 80# card stock from cutcardstock.com and the impression is... less impressive. The side by side results are pretty staggering (again, sorry for no photos right now!) I am rush ordering 110# card stock from them instead... Will need to do some thorough testing before committing to something for the invitations.

More significantly, I've stressed a bunch about the acrylic plates again being the wrong thickness. I left the blue backing on a Boxcar plate as a dry run without sticking it to the acrylic, and to my horror I couldn't feed it through. I tried, hard, and ended up permanently warping the plate. Thankfully this is one that I've already laser cut and wasn't planning on inking, so it's expendable. But when I took off the backing, it rolled through ok... I'm wondering, how hard should I need to crank the rollers? I'm having to crank them pretty hard to get it to roll through at the moment - just on the cusp of feeling like I'm doing damage. I'm actually a little worried that the 110# card stock will make enough of a difference that the crazy smushing/refusal to roll at all will happen again. What was your experience? As always, THANK YOU!

**Comment by jdleslie** [comment]
Sounds like things are coming together! (perhaps with a bit more pressure than desired, but together nonetheless)

> where along the 32" long sheet did you mount the pins?

I offset about 8 inches to ensure at least one side would have excellent outfeed support, and regret that decision. Centering the pins on the middle of the bottom plate would have been better as I have one side with an excess of support and the other is  marginal (still usable, but easy to feed it all the way out of the press).

Feeding from both directions eliminates the need to reset/shuttle the bottom plate back through the press between passes. The bottom plate is heavy, so eliminating this extra "reset" step is a significant benefit during production.

> I'm wondering, how hard should I need to crank the rollers?

Hard enough that you definitely need to use the crank (can't just push the bottom plate through the press), but there should be plenty of extra clearance before the press jams. You will need this clearance to adjust impression (Scotch tape, Blue tape, etc.) in case you have big blocks of text or large printed areas that need more impression than the other elements on the plate.

I got out the calipers to measure our actual plates today:
- **Bottom Plate:** 12.0mm (very consistent), nominally 1/2 inch
- **Top Plate:** 9.5mm (varies between 9.45mm and 9.52mm), sold as 3/8 inch

> I'm actually a little worried that the 110# card stock will make enough of a difference that the crazy smushing/refusal to roll at all will happen again. What was your experience?

After ordering every sampler pack Google could find, we ended up using:

| Application | Brand | Family | Weight | Rationale |
| --- | --- | --- | --- | --- |
| Invites, Thank You cards, inside of programs, and everything else | [Reich](http://www.reichpaper.com/) | [Savoy](http://www.reichpaper.com/savoy.html) | 118# | Comes in 8.5x11, nice impression |
| Envelopes | [Reich](http://www.reichpaper.com/) | [Savoy](http://www.reichpaper.com/savoy.html) | 80# | Matches paper for invitations, used [Henry gage "pins"](http://www.boxcarpress.com/shop/henry-gage-pins/) for alignment |
| Program Covers (outer) | [French](http://frenchpaper.com/) | [Pop Tone](http://www.frenchpaper.com/paper/by-line/pop-tone.html) | Cover 65# | Comes in 8.5x11, needed contrasting color |
- The Savoy paper seemed as nice as [Lettra](http://www.crane.com/business/business-papers-invitations-and-announcements/lettra-letterpress) and [Somerset](http://www.legionpaper.com/somerset/). Somerset was our first choice, but proved difficult/expensive to source in a shippable size (full "parent" sheets are impractical to ship via UPS). We were [almost able to source from Blick](http://www.dickblick.com/products/somerset-printmaking-paper/), but it turned out they couldn't actually get the goods listed on their web site. People who do this for a living undoubtedly know how to deal with transporting and cutting parent sheets of stock, but did not want to actually own any large-scale equipment (12-inch paper cutter is big enough!)
- Savoy 8.5x11 was weirdly sized compared to most copy paper. I think they cut it to the nearest metric dimension (215x280 mm?). Made no difference to finished product, but we had to ensure the plates were aligned to the center (not edge) of the paper

Best of luck!

**Comment by carlygeehr** [comment]
Whew! Well, it was an adventure, but we got the save the dates done. Barely.
![2016-03-08 22 43 05](https://cloud.githubusercontent.com/assets/1396364/13682540/0ab58a3a-e6b7-11e5-82f0-3c927675adae.jpg)

# Acrylic Plate Thickness Woes

My bottom plate is consistently .455" (significantly thinner than your 12mm, I'm surprised there's such a difference) and my top plate was between .364" - .369". This was the plate that was making me nervous about binding up the rollers and smashing the crud out of the paper, so I went to TAP and lo and behold they had some 3/8" pieces in scrap. Armed with calipers, I picked out a .345" and a .355" piece. Unfortunately, the .345" piece worked best impression-wise but was also tiny (about 8" x 9"). This whole setup can be shimmed if the plates are too thin, but you're S.O.L. if they're too thick. I think you got lucky with your plastic & your machine, since there's probably some variance in the roller thickness. Fiskars probably doesn't have super tight tolerances... To move forward, I'll need to go back to the store and insist that my pieces are as close to .345" as possible. I've wasted a ton of money so far on unusable acrylic!

# Crappy Paper

I learned the hard way that picking crappy paper is a bad idea. I got cheap 110# card stock and it looks cheap and sad.

# Crappy Brayer

Man, that Speedball thing is a P.O.S. Bald spots for days, not really big enough in diameter to get across the whole design without overlapping... Yikes. Not psyched about buying a $200 Takach brayer, but I'm not taking any more chances going forward.

# Ink Woes

I got a tub of Van Son ink custom mixed, and instead of it being the blueish gray (Pantone 432) I'd envisioned, it's just black. You can see in the picture - there's no subtlety or gentleness, it's just blast-your-eyeballs black. I can't blame the brayer or the paper for that, either. Now I'm stuck with a whole tub of it. I'm really, really bummed about that ink.

We did the run of "gray" first and that actually went fine. I over-inked some, but I got the hang of it as I went. A couple nights ago I moved on to the second color - and the PMS 871 gold from the tube (http://www.nagraph.com/ink.html) just would NOT come out. Once I'd finally managed to coax some onto the mixing plate, I poked it with the ink knife and it just acted like a solidified lump of hot glue. Didn't even stick to the knife. I HAD to get them done ASAP, so with some furious googling and a quick test I discovered that canola oil (yes, I'm cringing too) did just enough in a pinch to loosen the stuff up. I think I could buy some tac reducer to help out in the future, but I'm pretty turned off to that brand now and will probably just throw out that disastrous tube of ink.

I didn't take pictures of my setup for this, but there were splotches of the hardened ink all over the place as I was braying, and the brayer was sliding all over the place as I applied the ink... to make things worse, I ended up having to hand-roll the brayer without a fixture, since the brayer was too small for the area I needed to cover (yes, this was my bad) and I needed to do multiple passes... It was truly an unmitigated disaster. I'm pretty embarrassed at how they turned out but also amazed that we actually got them all "done". They're SO different from how they should/could look.

"Gray" Process shot:
![2016-03-06 21 07 39](https://cloud.githubusercontent.com/assets/1396364/13683147/0c7d692a-e6ba-11e5-8e63-49efb6cf37ac.jpg)

# Onward

I'm still in love with blind impressions (see random spotty pattern on the Save the Date) and would like to redeem this process, so I'm moving forward, armed with my mistakes and a completed (although mediocre at best) project under my belt. I will go ink-less wherever I can while designing these: going to attempt the invites, RSVP card, thank-you cards, and a little belly band thing. A lot of this hinges on finding a large enough piece of the 3/8" acrylic in the exact thickness I need. I can't do all the aforementioned pieces one at a time with an 8" square. Well, I could, but that would consume my life for about a month. At this point I've invested so much in the setup, I can't NOT move forward.

Addressed the envelopes last night, mailed them off today. I'm down, but not out!

**Comment by jdleslie** [comment]
Congrats on getting Save the Dates printed and posted!

## Debugging the inking process

Debugging the inking process is really painful. I spent hours of quality time printing test pieces, and figuring out ink almost drove me to drop the effort. In the end the practice was helpful, but the solution was equipment: better brayer and better support for the brayer when applying ink to the plate. It was kind of miraculous how simple and fast things were once the last of the process issues were worked out. We then branched out to new ink colors and paper with only a handful of test pieces.

That brayer situation looks frustrating. I wrote up my process on GitHub months after I finished printing wedding stuff, so I probably forgot some of my more frustrating moments with the Speedball brayer in the original writeup. There are people out on the Internet who claim to have figured out how to make it work well, and others who find it [challenging](http://www.boxcarpress.com/blog/l-letterpress-printing-results/). I am in the latter camp, and found the Takach brayer to be something of a revelation. On the plus side, you will definitely appreciate the quality of a Takach brayer, and the quality could make the price seem totally worth it! :+1: 

I imagine that big printed area with the thin negative details was fun to print. We also struggled with thin detail and ink creeping up the sides of the impression (this ink below is a mix of Van Son Orange with Black):
![table cards](http://jdleslie.smugmug.com/Projects/FuseLetterpressWiki/i-tj5XRbX/0/X3/IMG_1999-X3.jpg)

## Ideas
- Have you thought about flattening and/or thickness-ing an out-of-spec plate via ShopBot/CNC? Removing 1/32-inch from one of your thicker pieces would make them the same thickness as your best top plate. [This sort of process](http://www.instructables.com/id/Use-a-ShopBot-CNC-router-table-to-plane-down-a-lar/) works really well for wood pieces too large to fit through a [thickness planer](http://en.wikipedia.org/wiki/Thickness_planer) (e.g. table tops, butcher block counters, etc.). You might also think about making a custom thickness base out of MDF using this method (or a normal woodshed planer, which could do this in one or two passes) to suit the over-thickness top plates you have (assuming they are reasonably flat).
  - Even though the material was sold as 3/8-inch, my sheets look to be [9mm thickness Evonik Acrylite](https://www.acrylite-shop.com/US/us/cast-d10z0nzeyxr/acrylite-cast-gp-colorless-0f00-gt-1fqhmd1rx26~p.html). Sadly the actual thickness of the material you have would be within tolerance [based on their product specs](http://www.eplastics.com/Plastic/plastics_library/Thickness-Tolerances-of-Acrylic-Sheet-Plexiglass), so I guess the takeaway is that you are stuck inspecting sheet goods in person with calipers. Ugh
  - Would not be surprised if the print height of the press can be calibrated or otherwise factory-adjustable. I've never taken the plastic covers off my press...
  - I think the junky Fiskars dies work by adding a hard rubber to the "sandwich" on the bottom of a fairly thin top plate. Under-sizing the acrylic and adding some rubber to the sandwich might be a workable solution to for warped/under/over-sized acrylic. Clearly Fiskars is not producing high-tolerance dies and plates at their craft product price point
- A few drops of linseed oil might help thin the blue/black ink. 
  - [Accent Arts in Palo Alto](http://www.yelp.com/biz/accent-arts-palo-alto) has a good selection and is also where we bought paper for test prints. Regrettably they don't really have any letterpress printing ink, and don't really know anything about the letterpress printing process
  - A more sturdy brayer will allow you to roll out thinner layers of ink, which could improve transparency (in addition to bleed, etc.)

## What comes next

Paper cutting? We had some challenges achieving the level of consistency we would have liked with the rotary cutter, mainly due to operator error. The actual cut quality is excellent, but so much manual alignment (we aligned to the printed piece, not the edge of the paper) is both good (can salvage pieces with dirty/damaged edges) and bad (lots of opportunity to cut the edge so that is is not square to the printed content)

So many "seconds":
![seconds](http://jdleslie.smugmug.com/Projects/FuseLetterpressWiki/i-NRxG3WJ/0/X3/2016-03-11%2013.34.03-crop-X3.jpg)
(focus is poor in above photo-- the printing is sharp in person, but iPhone's macro depth of field is narrow...)

Appreciate the update!

**Comment by jdleslie** [comment]
Above comment was written not-so-well-- fixed it up!

![small tub of ink](https://cloud.githubusercontent.com/assets/7761335/13711391/4d96a03e-e78c-11e5-8c6f-ef6b4ebe219a.jpg)

Also: I sourced some silver metallic Van Son ink repackaged in smaller quantities from eBay last year. I see the same [seller](http://www.ebay.com/usr/adamsletterpress?_trksid=p2047675.l2559) also has [gold](http://www.ebay.com/itm/VanSon-Unipak-PMS-871-Metallic-Gold-oil-based-pirnting-ink-4-0oz-/321853272973?hash=item4aeff3338d:g:Sv0AAOSwd0BV6JRa) available. The smudge of color on the label is the color it actually prints...

**Comment by carlygeehr** [comment]
Ah, I didn't see the most recent addition! I continued to have bad luck with the custom Van Son mixes. As I mentioned before, the "gray" was actually black. I read that the solution is to add opaque white until you get the actual color - but the only quantity I could find opaque white in was something absurd like 3-5lbs and over $100 - not something I wanted to spend after splurging on a Takach brayer!! So, I got tricky - I also wanted a very, very light pink:
![image](https://cloud.githubusercontent.com/assets/1396364/14002165/59ef59f0-f107-11e5-9689-58ad1ebd21a2.png)
And since you can order custom blends at under $60 (cheaper if you buy direct from Van Son, since there are no shipping charges) I figured that this pink could act as my "white" and make my black less black... Well, joke was on me:

![2016-03-23 14 58 04](https://cloud.githubusercontent.com/assets/1396364/14002213/bf0bb7e8-f107-11e5-9840-7a1280c00f8a.jpg)
Yes, that ink can/poop smear are supposed to be that delicate light pink. ??!?!?!? I called Van Son and the guy was very friendly but totally unhelpful. He just said that all the colors are individually matched before they leave - so I'm thinking it's MY problem because what are the odds that I would order 2 colors and have them be so equally far from what I was expecting?! BUT - I discovered Ebay (hence why I wish I'd read your most recent addition to the thread... facepalm) and bought a 1-lb tub of white for under $30. That should come Friday - and then I'll get to experiment with mixing and trying to get the colors I thought I was buying.

Still no idea why the inks are SO FAR OFF the Pantone swatches. The best guess from the larger interwebs is that this ink is really designed for offset printing and thus would be much, MUCH thinner... but I don't buy it. The guy on the phone told me I was doing it right, and smearing it with a palette knife like I did should have shown it at its lightest value.

In the meantime...
I went by TAP and since I'm there so often buying scraps for the lab (200+ at a time) the guy spent a long time helping me find a transparent piece in the exact thickness I needed. Bless him!! Turns out the green-edged cast acrylic was consistently thinner. Go figure. Good enough for me!

Question for you - how did you go about chopping up your pieces? I have a 24" Rototrim in my lab and will also be using the 8.5x11" Reich Savoy paper. I figure I can fit 3 cards onto one sheet (the invite, the reply card, and the details card) but am wondering about spacing and crop marks - do you suggest butting them up together or leaving space in between?

![image](https://cloud.githubusercontent.com/assets/1396364/14002481/8f99b7f6-f109-11e5-8d9a-b1891c3f5dde.png)

I imagine that the advantage of having them all touching is that there are fewer cuts - but on the flipside, if you screw up one, you screw up all of them. Did you print crop marks? I'm getting my plates ready to get sent out and would love your advice!

Thank you, as always!!

**Comment by jdleslie** [comment]
Ink situation sounds terrible-- I will be sure not to order custom Van Son mixes! We mixed our own ink from Van Son stock colors and stored it in [little jam jars](http://www.amazon.com/Nakpunar-Glass-Wedding-Favors-Shower/dp/B00D52SK8O) (bonus: jam for breakfast!). I kept notes on how many ounces of each color went in, but ended up making running changes anyway, so I guess it's a limited edition...

## Layout

I like to leave space between the pieces and make extra cuts when finishing-- printing is slow and cutting is fast, so extra cuts are not a big deal in terms of production time. The extra space allows for more handling if you need to apply adhesives or don't have time to get all the cutting and envelope stuffing done at once.

If your brayer is 6-8" wide then you will want a place in the middle of the page for the brayer support to lay when inking. 
- Registration marks in center of plate interfere with this center brayer support. It is possible to lay a special brayer support inside the design, but the process will be messy and (really) slow things down...
- Wider is better! I think my design was about 16pt of brayer support, which was not as much as I would have liked

Three cards per sheet is a good way to go (two of my three plates were set up this way). It's OK for two stacked pieces (e.g. your smaller pieces above) to share a common short edge (as you have done), but not great when pieces share a long edge and have different heights (as your small pieces do above).
- In your above design I would keep everything far apart.
- If the small pieces were the same finished dimensions, I would group them to share a single cut along their short edges (sides) and a single cut to separate them. The final cut in this case would be easy to set up as you are halving the piece. When the pieces are different heights the errors compound and you will probably want to trim each piece individually

## Crop Marks and Cutting

I added far too many crop marks in most of my (early) plate designs, but did end up using some of the marks for cutting/finishing. They are easy to remove if they get in the way...
- My preferred crop mark is pair of 0.25pt lines separated by 2-3pts of white space. Fine lines with no design around them do not ink well (e.g. a lone 0.25pt line), but ganging two of them up to be ~3pt wide makes results in a more clearly defined printed result.
  - Only one of the lines is used (typically the one closest to finish piece) as second is just there to help support the brayer
  - You can also rough-cut with confidence and speed if you cut between the lines!
- Definitely do not cut crop marks out of the photopolymer plate and try to stick them in the right location on the top plate. This sometimes means a much larger plate order, but it is totally worth the extra square inches to have perfectly placed marks (sticking loose crop marks to the plate by hand is really time-consuming and hard to do straight/square/well).
- Registration marks are really useful to cut off the short edge of the page where the alignment holes are punched, as your design will not always be located exactly where you want it on the plate (e.g. at an angle). I typically cut off the alignment holes first, and making the first cut perfectly square to the design helps make subsequent cuts easier (square-ness of your cutter is really important!)
- My preferred approach is to have the largest piece on the page have either registration marks outside the finished area or add a straight border in the design. Cutting outside a straight border is easier/faster to than small registration lines at top and bottom of piece
- Cut from largest to smallest piece
- I thought i would have a lot of "program cutting" where the unfinished pieces would all be the same dimensions. In practice they were all subtly different, and doing them by eye ended up yielding better results...

Happy design (and production)!

**Comment by carlygeehr** [comment]
![image](https://cloud.githubusercontent.com/assets/1396364/14506043/a7d662ca-0170-11e6-9b1d-a8855119d50e.png)

Well, we're in production mode again! This time, things are going _much_ better. The white ink I ordered off Ebay was all crusted over and seriously gross, but there was enough usable ink to mix with my "gray" ink that I was actually able to get the color I wanted!!! 
![image](https://cloud.githubusercontent.com/assets/1396364/14503038/18dc4088-0163-11e6-987f-580c3fb62303.png)
vs
![image](https://cloud.githubusercontent.com/assets/1396364/14503077/4a573cee-0163-11e6-8ef7-eddd4311da4d.png) 
(Bad/zoomed in photo - but you can see the color difference from the samples I showed before)

I barely used any "gray" at all in mixing that up - this color was almost entirely opaque white. Crazy how strong the stuff they sent me was. Hoping when I get to my "pink" I can get similarly awesome results.

The Takach brayer? AMAZING. Wow. I feel like such a badass wielding that thing, and the results are fantastic. The 8" of uninterrupted travel was a lifesaver - saved a ton of time not having to re-ink.

Also, the Reich paper is totally voluptuous! Yowza! I couldn't believe it when I opened the package. A stack of 250 practically reaches the moon.

I am still having issues with the bite being really pronounced at the ends of the travel. Meaning, right where the plate first enters the roller (and the last part where it exits), there's a far more exaggerated impression than elsewhere. If I were more picky about things I'd probably put some kind of spacer in there, but oh well. I can live with this.

For cutting, since I was already going to do some blind impressions on the invites, I decided to just outline each piece with a .5pt line - I'll cut along those. We'll see how it goes. I gave up going for perfection long ago, but I thought that this would at least make things easier/more difficult to screw up! I don't have borders on any of my designs, so there's really nothing else to align them. I'm doing the blind impressions tonight, we'll see how it goes!

**Comment by jdleslie** [comment]
Am more than a bit envious of your expansive (and likely air conditioned) production setup!

I guess the takeaways are coalescing around:
- Practice makes perfect?
- Takach brayer is not really optional
- Not much point in doing this without the fluffy cotton paper

Really glad to hear you are getting good results-- impression around the "rsvp" looks great and the inking looks nicely uniform! As to how to even out impression, an extra brayer strip on the bottom or top plate sometimes helps (but also gets in the way) and Scotch tape under the part of the paper with lighter impression can help even things out. 

Or just don't worry about it. How likely is it that anyone who has not done a similar crash-course in relief printing will notice subtle variation in depth of impression...

Congrats! (and happy paper-cutting) 👍

**Comment by carlygeehr** [comment]
Hey, just wanted to drop you a line and express my sincere gratitude again. This has been such a crazy adventure and I'm so glad I did it, but I couldn't have done it without your guidance and initial inspiration! I'm now done with all the printing (the pink ink was eventually beautiful, but needed a similar amount of coaxing with what I could scrape out from the white opaque Ebay ink can) and am putting finishing touches on things... because I'm apparently clinically insane.

![2016-05-17 21 53 09](https://cloud.githubusercontent.com/assets/1396364/15487744/8edc6298-2104-11e6-9955-5cf99ecb6864.jpg)

Cutting was NOT fast, but it was easy to do in small batches and thus not totally overwhelming :-) The blind impression cut lines actually worked quite well and I'd gladly do it that way again. It ended up being faster/more effective to eyeball things than to try to set up an alignment edge. I think the Rototrim I was using was just slightly off.

![image](https://cloud.githubusercontent.com/assets/1396364/15487854/72ba95a2-2105-11e6-97fe-bc2332ba4632.png)

Excited to be finally wrapping these up! Lots of calligraphy ahead, and then send these puppies on their way. Almost a shame to dump them in a mailbox...

Have you done more "letterpress" projects since? Post-wedding I think I'll be looking for ways to keep my Fuse busy!!

**Comment by jdleslie** [comment]
Invites look great-- congrats on finishing the run! I am very glad that at least one other person was inspired (and successful) in doing this.

As you may know already, the cotton envelopes that match the letterpress stock might not fare well in the mail (they attract dirt, oil, etc.). We used them anyway, but I would use normal (far less expensive) paper envelopes in the future.

![wedding program](http://photos.smugmug.com/photos/i-w96nCzH/2/L/i-w96nCzH-L.jpg)
After invitations we decided to do print the programs ourselves (restricting length to two pages streamlined the writing process!). Programs went a lot more efficiently than the first print job, despite being a more elaborate process (adhesive, metallic ink, etc.).

![coda](http://photos.smugmug.com/photos/i-gkZfJHp/0/M/i-gkZfJHp-M.jpg)

We plan to print stationery and this year's Christmas cards on the Fuse, but are mostly doing house projects with wood these days-- look forward to a future GitHub projects on CNC-ing kitchen cabinet carcasses, turning rough lumber into Craftsman-style doors and windows, etc.

According to Wikipedia paper is a [traditional first anniversary gift](http://en.wikipedia.org/wiki/Wedding_anniversary)...
